name: 'Accessibility Gate (a11y-ci)'
description: 'Runs a11y-ci policy gate with unified artifact handling.'
inputs:
  artifact-dir:
    description: 'Directory to store artifacts'
    required: false
    default: '.a11y_artifacts'
  current:
    description: 'Path to current scorecard JSON (optional if in artifact-dir)'
    required: false
  baseline:
    description: 'Path to baseline scorecard JSON (optional if in artifact-dir)'
    required: false
  allowlist:
    description: 'Path to allowlist JSON (optional if in artifact-dir)'
    required: false
  fail-on:
    description: 'Minimum severity to fail on (info, minor, moderate, serious, critical)'
    required: false
    default: 'serious'
  top:
    description: 'Limit N blocking findings in output'
    required: false
    default: '10'
  platform:
    description: 'Markdown flavor for PR comments (github or ado)'
    required: false
    default: 'github'
  post-comment:
    description: 'Whether to prepare a PR comment file'
    required: false
    default: 'true'

outputs:
  exit_code:
    description: 'Exit code of the gate'
    value: ${{ steps.gate.outputs.exit_code }}
  evidence_path:
    description: 'Path to the generated evidence JSON'
    value: ${{ steps.gate.outputs.evidence_path }}
  comment_path:
    description: 'Path to the generated PR comment markdown'
    value: ${{ steps.gate.outputs.comment_path }}
  gate_result_path:
    description: 'Path to the generated gate result JSON'
    value: ${{ steps.gate.outputs.gate_result_path }}

runs:
  using: "composite"
  steps:
    - name: Run Accessibility Gate
      id: gate
      shell: bash
      run: |
        # 1. Setup Artifacts
        ARTIFACT_DIR="${{ inputs.artifact-dir }}"
        mkdir -p "$ARTIFACT_DIR"
        echo "Using artifact directory: $ARTIFACT_DIR"
        
        # 2. Construct Arguments
        ARGS="gate --artifact-dir $ARTIFACT_DIR"
        
        if [ -n "${{ inputs.current }}" ]; then
          ARGS="$ARGS --current ${{ inputs.current }}"
        fi
        
        if [ -n "${{ inputs.baseline }}" ]; then
          ARGS="$ARGS --baseline ${{ inputs.baseline }}"
        fi
        
        if [ -n "${{ inputs.allowlist }}" ]; then
          ARGS="$ARGS --allowlist ${{ inputs.allowlist }}"
        fi
        
        ARGS="$ARGS --fail-on ${{ inputs.fail-on }}"
        ARGS="$ARGS --top ${{ inputs.top }}"
        
        # 3. Run Gate
        echo "Running: a11y-ci $ARGS"
        
        # Run and capture exit code, but don't fail immediately so we can process artifacts
        set +e
        a11y-ci $ARGS
        EXIT_CODE=$?
        set -e
        
        echo "Gate Exit Code: $EXIT_CODE"
        echo "exit_code=$EXIT_CODE" >> $GITHUB_OUTPUT
        
        # 4. Generate Comment (if requested and evidence exists)
        EVIDENCE_JSON="$ARTIFACT_DIR/evidence.json"
        COMMENT_MD="$ARTIFACT_DIR/comment.md"
        GATE_RESULT="$ARTIFACT_DIR/gate-result.json"
        
        if [ "${{ inputs.post-comment }}" = "true" ] && [ -f "$EVIDENCE_JSON" ]; then
           echo "Generating PR Comment..."
           a11y-ci comment --mcp "$EVIDENCE_JSON" --platform "${{ inputs.platform }}" --top "${{ inputs.top }}" > "$COMMENT_MD"
           echo "comment_path=$COMMENT_MD" >> $GITHUB_OUTPUT
        fi
        
        # 5. Set Outputs
        echo "evidence_path=$EVIDENCE_JSON" >> $GITHUB_OUTPUT
        echo "gate_result_path=$GATE_RESULT" >> $GITHUB_OUTPUT
        
        # 6. Exit with code
        exit $EXIT_CODE
