"""Canonical error IDs for a11y-ci."""

# Input / Configuration Errors (Exit Code 2)
INPUT_SCHEMA_INVALID = "A11Y.CI.INPUT.SCHEMA.INVALID"
INPUT_MISSING_FILE = "A11Y.CI.INPUT.MISSING.FILE"
INPUT_INVALID_FORMAT = "A11Y.CI.INPUT.INVALID.FORMAT"
INPUT_ARGUMENT_ERROR = "A11Y.CI.INPUT.ARGUMENT.ERROR"

# Gate Failures (Exit Code 3)
GATE_THRESHOLD_EXCEEDED = "A11Y.CI.GATE.THRESHOLD.EXCEEDED"
GATE_REGRESSION_COUNT = "A11Y.CI.GATE.REGRESSION.COUNT"
GATE_REGRESSION_NEW_ID = "A11Y.CI.GATE.REGRESSION.NEW_ID"
GATE_ALLOWLIST_EXPIRED = "A11Y.CI.GATE.ALLOWLIST.EXPIRED"
GATE_ALLOWLIST_INVALID = "A11Y.CI.GATE.ALLOWLIST.INVALID"

# Internal Errors (Exit Code 1)
INTERNAL_ERROR = "A11Y.CI.INTERNAL.ERROR"
