"""
PR Comment Formatter for a11y-ci evidence.
Renders MCP payloads into GitHub or ADO Markdown.
"""

from __future__ import annotations

from typing import Any, Dict, List

def render_pr_comment(payload: Dict[str, Any], *, platform: str = "github", top: int = 10) -> str:
    """Render an MCP payload as a Markdown PR comment."""
    is_github = platform == "github"
    
    # 1. Header
    gate = payload.get("gate", {})
    decision = gate.get("decision", "unknown").lower()
    pass_icon = "✅"
    fail_icon = "❌"
    
    if decision == "pass":
        title = f"{pass_icon} Accessibility Gate: PASS"
    else:
        title = f"{fail_icon} Accessibility Gate: FAIL"
        
    lines = [f"# {title}", ""]

    # 2. Summary Table
    counts = gate.get("counts", {})
    deltas = gate.get("deltas", {})
    fail_on = gate.get("fail_on", "serious")
    
    lines.append("| Metric | Value | Delta |")
    lines.append("|:---|:---|:---|")
    lines.append(f"| **Fail Threshold** | `{fail_on}` | - |")
    
    # Sort severities for consistent display
    severities = ["critical", "serious", "moderate", "minor", "info"]
    has_counts = False
    for sev in severities:
        if sev in counts:
            has_counts = True
            count = counts[sev]
            delta = deltas.get(sev, 0)
            delta_str = f"{delta:+d}" if delta != 0 else "-"
            # Highlight failing severities
            # Roughly: if sev >= fail_on and delta > 0 or absolute count issues
            # For table simplicity, just list them.
            lines.append(f"| {sev.title()} | {count} | {delta_str} |")

    if not has_counts:
         lines.append("| Findings | 0 | - |")

    lines.append("")
    
    # 3. Blocking Findings (Top N)
    blocking = payload.get("blocking", [])
    if blocking and top > 0:
        lines.append("## 🚫 Blocking Findings")
        if len(blocking) > top:
             lines.append(f"_Showing first {top} of {len(blocking)} violations_")
        
        # Sort by severity (rank) then ID for stability
        # We need a rank map
        severity_rank = {k: i for i, k in enumerate(reversed(severities))}
        
        def sort_key(item):
            s = item.get("severity", "info")
            r = severity_rank.get(s, 0)
            return (-r, item.get("id", ""))

        sorted_blocking = sorted(blocking, key=sort_key)
        
        for item in sorted_blocking[:top]:
            fid = item.get("id", "UNKNOWN")
            severity = item.get("severity", "info").upper()
            msg = item.get("message", "No message provided")
            loc = item.get("location") or "Unknown location"
            hint = item.get("help_hint")
            url = item.get("help_url")
            
            # Formatting
            if is_github:
                header = f"### [{severity}] {fid}"
            else:
                header = f"### {severity}: {fid}"
                
            lines.append(header)
            lines.append(f"> {msg}")
            lines.append("")
            lines.append(f"- **Location**: `{loc}`")
            if hint:
                lines.append(f"- **Fix**: {hint}")
            if url:
                lines.append(f"- **Docs**: [Read Guidance]({url})")
            lines.append("")


    # 4. Artifacts
    artifacts = payload.get("artifacts", [])
    if artifacts:
        lines.append("## 📦 Artifacts")
        lines.append("| Kind | SHA256 Hash |")
        lines.append("|:---|:---|")
        for art in artifacts:
            kind = art.get("kind", "unknown")
            sha = art.get("sha256", "unknown")
            # Truncate hash for readability
            short_sha = sha[:12] + "..." if len(sha) > 12 else sha
            lines.append(f"| {kind} | `{short_sha}` |")
        lines.append("")

    # 5. Footer
    tool_ver = payload.get("tool_version", "unknown")
    repo = payload.get("repo")
    sha = payload.get("commit_sha")
    run_id = payload.get("run_id", "").split("-")[-1]  # Short run ID
    
    footer_parts = [f"Generated by **a11y-ci v{tool_ver}**"]
    if sha:
        footer_parts.append(f"Commit: `{sha[:7]}`")
    if run_id:
        footer_parts.append(f"Run: `{run_id}`")
        
    lines.append("---")
    lines.append(" | ".join(footer_parts))
    
    return "\n".join(lines)
