
import json
import pytest
from a11y_ci.pr_comment import render_pr_comment

@pytest.fixture
def sample_payload():
    return {
        "tool": "a11y-ci",
        "tool_version": "1.0.0",
        "repo": "org/repo",
        "commit_sha": "abcdef123456",
        "run_id": "run-xyz-789",
        "gate": {
            "decision": "fail",
            "fail_on": "serious",
            "counts": {"serious": 2, "minor": 5},
            "deltas": {"serious": 2}
        },
        "blocking": [
            {
                "id": "A11Y.IMG.ALT", 
                "severity": "serious", 
                "message": "Missing alt text", 
                "location": "logo.png",
                "help_hint": "Add alt='logo'",
                "help_url": "http://docs/img-alt"
            },
            {
                "id": "A11Y.BTN.NAME", 
                "severity": "critical", 
                "message": "Button empty", 
                "location": "btn.js"
            }
        ],
        "artifacts": [
             {"kind": "scorecard", "sha256": "aabbccddeeff0011223344"}
        ]
    }

def test_render_fail_github(sample_payload):
    """Test standard GitHub failure output."""
    md = render_pr_comment(sample_payload, platform="github")
    
    # Header
    assert "❌ Accessibility Gate: FAIL" in md
    
    # Table summary
    assert "| Serious | 2 | +2 |" in md
    assert "| Minor | 5 | - |" in md
    
    # Blocking findings section
    assert "## 🚫 Blocking Findings" in md
    
    # Finding 1 (Critical should come first due to sorting)
    assert "### [CRITICAL] A11Y.BTN.NAME" in md
    assert "Button empty" in md
    
    # Finding 2 (Serious)
    assert "### [SERIOUS] A11Y.IMG.ALT" in md
    assert "**Fix**: Add alt='logo'" in md
    assert "**Docs**: [Read Guidance](http://docs/img-alt)" in md
    
    # Artifacts
    # hash is mock SHA 'aabbccddeeff0011223344', truncated to 12 chars + ...
    assert "aabbccddeeff..." in md
    
    # Footer
    assert "Generated by **a11y-ci v1.0.0**" in md
    assert "Commit: `abcdef1`" in md

def test_render_pass(sample_payload):
    """Test passing state."""
    sample_payload["gate"]["decision"] = "pass"
    sample_payload["blocking"] = []
    
    md = render_pr_comment(sample_payload, platform="github")
    
    assert "✅ Accessibility Gate: PASS" in md
    assert "🚫 Blocking Findings" not in md

def test_render_ado_flavor(sample_payload):
    """Test ADO-specific nuances (mostly header changes in this simplified impl)."""
    md = render_pr_comment(sample_payload, platform="ado")
    
    # Check H3 format distinct from GitHub fixture
    # GH: ### [CRITICAL] ID
    # ADO: ### CRITICAL: ID
    assert "### CRITICAL: A11Y.BTN.NAME" in md
    assert "### [CRITICAL]" not in md

def test_render_missing_optional_fields():
    """Should handle missing deltas/counts gracefully."""
    minimal_payload = {
        "gate": {
             "decision": "pass",
             "fail_on": "error"
        }
    }
    md = render_pr_comment(minimal_payload)
    assert "✅ Accessibility Gate: PASS" in md
    # Should show 0 findings in table
    assert "| Findings | 0 | - |" in md
